DROP TABLE user IF EXISTS;

CREATE TABLE user
(
    id     int GENERATED BY DEFAULT AS IDENTITY,
    name   varchar(100) DEFAULT NULL,
    gender int          DEFAULT 0,
    type   varchar(10)  DEFAULT NULL,
    PRIMARY KEY (id)
);

INSERT INTO user
VALUES (1, 'a', '1', NULL);
INSERT INTO user
VALUES (2, 'b', '0', NULL);
INSERT INTO user
VALUES (3, 'c', '1', '好人');